eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
 #配置服务显示名称
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

server:
  port: 8766

spring:
  application:
    name: zuul_service

zuul:
  routes:
    api-a:
      path: /feign/**
      serviceId: productServiceFeign
    api-b:
      path: /ribbon/**
      serviceId: productServiceRibbon
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

##timeout config
ribbon:
  ReadTimeout: 13000
  ConnectTimeout: 13000
  eureka:
    enable: true

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000

