spring:
  application:
    name: eureka-server
  profiles: peer2

server:
  port: 8222

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
