server:
  port: 8711

spring:
  application:
    name: orderService

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true